// site-react/src/app/genes/CategoryStats.tsx
import type React from 'react';
import { useState } from 'react';
import { Checkbox, Tooltip } from '@mui/material';
import { useAppSelector } from "../hooks";
import type { RootState } from "../store/store";
import { useGetGenesStatsQuery } from "./genesApiSlice";
import { ASPECT_MAP } from "@/@pango.core/data/config";

interface AspectOption {
  id: string;
  label: string;
  shorthand: string;
  description: string;
  color: string;
  icon: string;
}

interface CategoryItem {
  id: string;
  aspect: string;
  label: string;
  displayId: string;
  count: number;
  color: string;
  aspectShorthand: string;
  width: string;
  countPos: string;
}

const CategoryStats: React.FC = () => {
  const [selectedAspects, setSelectedAspects] = useState<string[]>(Object.values(ASPECT_MAP).map(aspect => aspect.id));
  const search = useAppSelector((state: RootState) => state.search);
  const filter = {
    geneIds: search.genes.map(g => g.gene),
    slimTermIds: search.slimTerms.map(t => t.id)
  };

  const { data: geneStats } = useGetGenesStatsQuery({ filter });
  const toggleAspect = (aspectId: string) => {
    setSelectedAspects(prev =>
      prev.includes(aspectId)
        ? prev.filter(id => id !== aspectId)
        : [...prev, aspectId]
    );
  };

  const buildCategoryBar = (buckets: any[]): CategoryItem[] => {
    if (!buckets?.length) return [];

    const filteredBuckets = buckets.filter(bucket =>
      selectedAspects.includes(bucket.meta.aspect)
    );

    const sortedBuckets = [...filteredBuckets].sort((a, b) => b.docCount - a.docCount);
    const longest = sortedBuckets[0]?.docCount || 0;

    return sortedBuckets.map((bucket) => {
      const ratio = bucket.docCount / longest;
      const countPos = ratio < 0.20 ? `${ratio * 100}%`
        : ratio < 0.90 ? `${(ratio - 0.15) * 100}%`
          : `${(ratio - 0.30) * 100}%`;

      return {
        ...bucket.meta,
        name: bucket.key,
        count: bucket.docCount,
        color: ASPECT_MAP[bucket.meta.aspect]?.color,
        aspectShorthand: ASPECT_MAP[bucket.meta.aspect]?.shorthand,
        width: `${ratio * 100}%`,
        countPos
      };
    });
  };

  const slimTermFrequency = geneStats?.slimTermFrequency?.buckets
    ? buildCategoryBar(geneStats.slimTermFrequency.buckets)
    : [];

  return (
    <div className="w-full">
      <div className="h-full">
        <div className="p-4 border-b border-gray-200">
          <h3 className="font-medium">GO Function Category Distribution</h3>
        </div>

        <div className="p-4">
          <h5 className="mb-4">Show/hide GO aspects in category list below</h5>

          <div className="flex flex-wrap gap-4 mb-6">
            {Object.values(ASPECT_MAP).map((aspect: AspectOption) => (
              <Tooltip
                key={aspect.id}
                title={aspect.description}
                placement="top"
                enterDelay={1500}
              >
                <div
                  className="flex items-center gap-2 p-2 rounded cursor-pointer"
                  style={{
                    backgroundColor: selectedAspects.includes(aspect.id)
                      ? `${aspect.color}50`
                      : '#EEEEEE'
                  }}
                  onClick={() => toggleAspect(aspect.id)}
                >
                  <Checkbox
                    checked={selectedAspects.includes(aspect.id)}
                    onChange={() => toggleAspect(aspect.id)}
                    onClick={(e) => e.stopPropagation()}
                    size="small"
                    sx={{
                      color: `${aspect.color}50`,
                      '&.Mui-checked': {
                        color: aspect.color,
                      },
                    }}
                  />
                  <img
                    src={`assets/images/activity/${aspect.icon}.png`}
                    alt={aspect.label}
                    className="w-6 h-6"
                  />
                  <span className="text-sm">{aspect.shorthand}</span>
                </div>
              </Tooltip>
            ))}
          </div>

          {slimTermFrequency.map((item) => (
            <div
              key={item.id}
              className="flex items-center py-2 border-b border-gray-300 cursor-pointer hover:bg-gray-50"
            >
              <div
                className="mr-4 rounded-full text-xs font-extrabold h-9 w-9 flex items-center justify-center"
                style={{
                  border: `1px solid ${item.color}50`,
                  color: item.color,
                  backgroundColor: `${item.color}20`
                }}
              >
                {item.aspectShorthand}
              </div>

              <div className="w-[100px]">
                <div className="text-xs truncate">{item.label}</div>
                <div className="text-xs text-gray-500 italic truncate">
                  {item.displayId}
                </div>
              </div>

              <div className="flex-1 relative h-9">
                <div
                  className="h-full absolute"
                  style={{
                    backgroundColor: item.color,
                    width: item.width
                  }}
                />
                <div
                  className="absolute px-2 py-1 text-xs bg-white border border-gray-300 rounded-lg transform -translate-y-1/2"
                  style={{
                    left: item.countPos,
                    top: '50%'
                  }}
                >
                  {item.count} genes
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
};

export default CategoryStats;

// site-angular/src/app/main/apps/annotation/category-stats/category-stats.component.ts
import { Component, OnDestroy, OnInit } from '@angular/core';
import { pangoData } from '@pango.common/data/config';
import { SearchFilterType } from '@pango.search/models/search-criteria';
import { Subject } from 'rxjs';
import { takeUntil } from 'rxjs/operators';
import { GeneStats, Term } from '../models/annotation';
import { AnnotationPage } from '../models/page';
import { AnnotationService } from '../services/annotation.service';
import { PangoDataService } from '@pango.common/services/pango-data.service';

@Component({
  selector: 'pango-category-stats',
  templateUrl: './category-stats.component.html',
  styleUrls: ['./category-stats.component.scss']
})
export class CategoryStatsComponent implements OnInit, OnDestroy {
  SearchFilterType = SearchFilterType;
  aspectMap = pangoData.aspectMap;
  annotationPage: AnnotationPage;
  geneStats: GeneStats;
  showCategories: boolean = true;
  selectedAspects: string[] = [];
  slimTermFrequency = [];
  private _unsubscribeAll: Subject<any>;

  constructor(
    private annotationService: AnnotationService,
    public pangoDataService: PangoDataService
  ) {
    this._unsubscribeAll = new Subject();
  }

  ngOnInit(): void {
    // Initialize all aspects as selected
    this.selectedAspects = this.pangoDataService.aspectOption.options.map(aspect => aspect.id);

    this.annotationService.onGenesAggsChanged
      .pipe(takeUntil(this._unsubscribeAll))
      .subscribe((geneStats: GeneStats) => {
        if (geneStats) {
          this.geneStats = geneStats;
          this.generateStats();
          this.showCategories = true;
        }
      });

    this.annotationService.onAnnotationsChanged
      .pipe(takeUntil(this._unsubscribeAll))
      .subscribe((annotationPage: AnnotationPage) => {
        if (!annotationPage) {
          this.annotationPage = null;
          return;
        }
        this.annotationPage = annotationPage;
      });
  }

  toggleAspect(aspectId: string): void {
    const index = this.selectedAspects.indexOf(aspectId);
    if (index === -1) {
      this.selectedAspects.push(aspectId);
    } else {
      this.selectedAspects.splice(index, 1);
    }
    this.generateStats();
  }

  selectSlimTerm(term: Term): void {
    const slimTerms = this.annotationService.searchCriteria[SearchFilterType.SLIM_TERMS] || [];
    if (!slimTerms.some(t => t.id === term.id)) {
      slimTerms.push(term);
      this.annotationService.updateSearch();
    }
  }

  generateStats(): void {
    if (this.geneStats?.slimTermFrequency?.buckets) {
      const filteredBuckets = this.geneStats.slimTermFrequency.buckets
        .filter(bucket => this.selectedAspects.includes(bucket.meta.aspect));
      this.slimTermFrequency = this.annotationService.buildCategoryBar(filteredBuckets);
    }
  }

  ngOnDestroy(): void {
    this._unsubscribeAll.next(null);
    this._unsubscribeAll.complete();
  }
}
<div class="w-100-p" fxLayout="row" fxLayoutAlign="start stretch">
  <div class="pango-form-section pango-terms-stats h-100-p" fxFlex="" fxLayout="column" fxLayoutAlign="start stretch">
    <div class="pango-section-header" fxLayout="row" fxLayoutAlign="start center">
      <div class="pango-section-heading">
        <h3>GO Function Category Distribution</h3>
      </div>
      <span fxFlex></span>
    </div>

    <div class="pango-section-body pango-terms-cell" fxLayout="column" fxLayoutAlign="start stretch">
      <pango-term-form></pango-term-form>

      <div class="pango-section-heading">
        <h5>Show/hide GO aspects in category list below
        </h5>
      </div>
      <span fxFlex></span>

      <div fxLayout="row" fxLayoutAlign="start center" class="q-100-p mb-24">
        <div *ngFor="let aspect of pangoDataService.aspectOption.options" class="aspect-item"
          [style.background-color]="selectedAspects.includes(aspect.id) ? aspect.color+50 : '#EEEEEE'"
          matTooltip="{{aspect.description}}" [matTooltipPosition]="'above'" [matTooltipShowDelay]="1500"
          [ngClass]="{'selected': selectedAspects.includes(aspect.id)}" (click)="toggleAspect(aspect.id)">

          <mat-checkbox [checked]="selectedAspects.includes(aspect.id)" (change)="toggleAspect(aspect.id)"
            (click)="$event.stopPropagation()">
          </mat-checkbox>

          <img [src]="'assets/images/activity/' + aspect.icon + '.png'" [alt]="aspect.label">

          <span>{{aspect.shorthand}}</span>
        </div>
      </div>

      <div class="pango-activity-term-row" fxLayout="column">
        <div *ngFor="let item of slimTermFrequency" class="w-100-p pango-term-cell" (click)="selectSlimTerm(item)"
          fxLayout="row" fxLayoutAlign="start center">
          <mat-chip class="pango-chip-xs mr-4 pango-aspect {{item.aspectShorthand}}" fxLayout="column"
            fxLayoutAlign="center center">
            <span>{{item.aspectShorthand}}</span>
          </mat-chip>

          <div class="" fxFlex="100px" fxLayout="column" fxLayoutAlign="start start">
            <div class="pango-cell-title w-100-p">
              <span class="pango-cell-description pango-truncate">{{item.label}}</span>
              <span class="pango-cell-description-2 pango-truncate">{{item.displayId}}</span>
            </div>
          </div>

          <div fxFlex="" class="pango-bar-container">
            <div class="pango-stat-bar" [style.background-color]="item.color" [style.width]="item.width">
            </div>
            <div class="pango-cell-count" [style.left]="item.countPos">
              {{ item.count }} genes
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
