// site-react/src/app/layout/Toolbar.tsx
import type React from 'react';
import { useState } from 'react';
import { IconButton, Button, Menu, MenuItem, LinearProgress } from '@mui/material';
import { FaBars, FaGithub } from 'react-icons/fa';
import { Link } from 'react-router-dom';

interface ToolbarProps {
  openLeftDrawer: () => void;
  showLoadingBar?: boolean;
}

const Toolbar: React.FC<ToolbarProps> = ({ openLeftDrawer, showLoadingBar }) => {
  const [exportMenuAnchor, setExportMenuAnchor] = useState<null | HTMLElement>(null);

  const handleExportMenu = (event: React.MouseEvent<HTMLElement>) => {
    setExportMenuAnchor(event.currentTarget);
  };

  const handleCloseExportMenu = () => {
    setExportMenuAnchor(null);
  };

  return (
    <div className="fixed top-0 left-0 w-full h-[50px] bg-primary-500 text-accent-500 z-50">
      <div className="px-2 h-[50px] flex items-center relative">
        {showLoadingBar && (
          <div className="absolute top-0 left-0 right-0 w-full">
            <LinearProgress color="secondary" />
          </div>
        )}

        <IconButton
          color="inherit"
          onClick={openLeftDrawer}
          className="mr-2"
          size="large"
        >
          <FaBars />
        </IconButton>

        <div className="flex items-center h-full ">
          <Link to="/" className="no-underline hover:text-accent-200">
            <span className="text-2xl font-bold mr-1">PAN-GO</span>
          </Link>
          <Link to="/" className="no-underline hover:text-accent-200">
            <span className="text-2xl">Human Functionome</span>
          </Link>
        </div>

        <div className="hidden md:flex flex-1 justify-end items-center">
          <div className="flex items-center pr-3 text-accent-500">
            <IconButton
              color="inherit"
              href="https://github.com/pantherdb/pango"
              target="_blank"
              size="large"
            >
              <FaGithub />
            </IconButton>
          </div>

          <div className="flex items-center px-3 border-l border-accent-200">
            <Button
              color="inherit"
              className="!text-xl !text-accent-500 hover:text-accent-200"
              onClick={handleExportMenu}
            >
              Download
            </Button>
            <Menu
              anchorEl={exportMenuAnchor}
              open={Boolean(exportMenuAnchor)}
              onClose={handleCloseExportMenu}
            >
              <MenuItem component="a" href="https://functionome.org/download/export_annotations.zip">
                As CSV
              </MenuItem>
              <MenuItem component="a" href="https://functionome.org/download/export_annotations.json.gz">
                As JSON
              </MenuItem>
            </Menu>

            <Button
              color="inherit"
              component={Link}
              className="!text-xl !text-accent-500 hover:text-accent-200"
              to="/about"
            >
              About
            </Button>
          </div>

          <div className="flex items-center">
            <div className="flex items-center px-4 border-l border-accent-200">
              <a href="http://geneontology.org/" target="_blank" rel="noopener noreferrer">
                <img src="/assets/images/logos/go-logo-yellow.png" alt="GO Logo" className="h-11" />
              </a>
            </div>
            <div className="flex items-center px-4 border-l border-accent-200">
              <a href="http://pantherdb.org" target="_blank" rel="noopener noreferrer">
                <img src="/assets/images/logos/panther-logo-yellow.png" alt="Panther Logo" className="h-11" />
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Toolbar;

// site-angular/src/app/layout/components/toolbar/toolbar.component.ts
import { Component } from '@angular/core';
import { NavigationEnd, NavigationStart, Router, ActivatedRoute } from '@angular/router';
import { PangoMenuService } from '@pango.common/services/pango-menu.service';

@Component({
    selector: 'pango-toolbar',
    templateUrl: './toolbar.component.html',
    styleUrls: ['./toolbar.component.scss']
})

export class PangoToolbarComponent {
    showLoadingBar: boolean;

    constructor(
        public pangoMenuService: PangoMenuService,
        private router: Router,
    ) {

        this.router.events.subscribe(
            (event) => {
                if (event instanceof NavigationStart) {
                    this.showLoadingBar = true;
                }
                if (event instanceof NavigationEnd) {
                    this.showLoadingBar = false;
                }
            });

    }

    search(value): void {
        console.log(value);
    }

    openLeftDrawer() {
        this.pangoMenuService.openLeftDrawer();
    }

}

<div class="w-100-p" fxLayout="column" fxLayoutAlign="start stretch">
  <div class="pango-announcement" fxLayout="row" fxLayoutAlign="center center">
    <div class="pango-announcement-header text-center" fxLayout="row" fxLayoutAlign="center center">
      <p>Archived version 1.0 matching the PAN-GO publication. For the current version
        <a href="https://functionome.geneontology.org/" class="pango-version-link" target="_blank">here</a>.
      </p>

    </div>
  </div>
  <mat-toolbar fxLayout="row" fxLayoutAlign="start center">
    <mat-progress-bar *ngIf="showLoadingBar" class="loading-bar" color="accent" mode="indeterminate"></mat-progress-bar>
    <a (click)="openLeftDrawer()" class="pango-bars mr-8" aria-label="Close dialog">
      <fa-icon [icon]="['fas', 'bars']"></fa-icon>
    </a>
    <div class="pango-logo pl-0 h-100-p" fxLayout="row" fxLayoutAlign="start center" fxFlex="180px">
      <ng-container>
        <a class="pango-main-logo" href="/">
          PAN-GO
        </a>
        <a class="pango-sub-logo" href="/">
          Human Functionome
        </a>
      </ng-container>
    </div>


    <div fxLayout="row" fxHide.lt-md fxLayoutAlign="end center" fxFlex="">
      <div class="pango-br pr-12" fxLayout="row" fxLayoutAlign="start center">
        <a mat-icon-button href="https://github.com/pantherdb/pango" target="blank">
          <fa-icon [icon]="['fab', 'github']"></fa-icon>
        </a>
      </div>
    </div>
    <div class="pango-br pl-12 pr-12" fxHide.lt-md fxLayout="row" fxLayoutAlign="start center">
      <!-- <a mat-button [routerLink]="['/download']">Export</a> -->

      <a mat-button class="pango-icon-button" [matMenuTriggerFor]="exportMenu">
        Download
      </a>
      <mat-menu #exportMenu="matMenu" class="pango-dropdown-menu">
        <a mat-menu-item href="https://functionome.org/download/export_annotations.zip" class="">
          As CSV
        </a>
        <a mat-menu-item href="https://functionome.org/download/export_annotations.json.gz" class="">
          As JSON
        </a>
        <!--   <a mat-menu-item href="http://data.pantherdb.org/ftp/downloads/pango/export_annotations.zip" class="">
          As CSV
        </a>
        <a mat-menu-item href="http://data.pantherdb.org/ftp/downloads/pango/export_annotations.json.gz" class="">
          As JSON
        </a> -->
      </mat-menu>

      <a mat-button [routerLink]="['/about']">About</a>
    </div>
    <div class="pango-friends-logo" fxHide.lt-md fxLayout="row" fxLayoutAlign="start">
      <div class="pango-bl pango-logo" fxLayout="row" fxLayoutAlign="start">
        <a href="http://geneontology.org/" target="_blank">
          <img src="assets/images/logos/go-logo-yellow.png">
        </a>
      </div>
      <div class="pango-bl pango-logo" fxLayout="row" fxLayoutAlign="start">
        <a href="http://pantherdb.org" target="_blank">
          <img src="assets/images/logos/panther-logo-yellow.png">
        </a>
      </div>
    </div>

  </mat-toolbar>


</div>
