// site-angular/src/app/main/pages/home/home.component.ts
import { Component, OnInit, ViewChild } from '@angular/core';
import { UntypedFormGroup } from '@angular/forms';
import { ActivatedRoute, NavigationStart, Router } from '@angular/router';
import { MatDrawer } from '@angular/material/sidenav';

import { PangoMenuService } from '@pango.common/services/pango-menu.service';
import { LeftPanel, RightPanel } from '@pango.common/models/menu-panels';
import { AnnotationService } from 'app/main/apps/annotation/services/annotation.service';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.scss']
})
export class HomeComponent implements OnInit {
  RightPanel = RightPanel;
  LeftPanel = LeftPanel

  @ViewChild('leftDrawer', { static: true })
  leftDrawer: MatDrawer;

  @ViewChild('rightDrawer', { static: true })
  rightDrawer: MatDrawer;

  searchCriteria: any = {};
  searchForm: UntypedFormGroup;
  leftPanelMenu;

  loadingSpinner: any = {
    color: 'primary',
    mode: 'indeterminate'
  };

  scrollbarConfig = {
    suppressScrollX: true
  }

  constructor(public pangoMenuService: PangoMenuService,
    public annotationService: AnnotationService) {
  }

  ngOnInit() {
    this.annotationService.searchCriteria.clearSearch()
    this.annotationService.updateSearch();
    this.pangoMenuService.setLeftDrawer(this.leftDrawer);
    this.pangoMenuService.setRightDrawer(this.rightDrawer);
  }
}

<div class="w-100-p" fxLayout="row" fxLayoutAlign="start start">
  <mat-drawer-container class="w-100-p h-100-p" fxLayout="row" fxLayoutAlign="start start" autosize>
    <mat-drawer #leftDrawer class="pango-left-drawer" mode="side" position="start" opened="true">
      <div fxLayout="column" fxLayoutAlign="start stretch" class="pango-drawer h-100-p">
        <div class="pango-drawer-header" fxLayout="row" fxLayoutAlign="start center">
          <span class="pango-drawer-header-title"> Filter Options</span>
          <span fxFlex></span>
          <button mat-stroked-button type="button" color="warn" class="pango-rounded-button pango-xs mr-8"
            (click)="clearAllFilters()">
            Clear All Filters
          </button>
          <button mat-stroked-button (click)="closeLeftDrawer()" class="pango-rounded-button pango-xs" color="primary"
            aria-label="Close dialog"
            matTooltip="Expand your viewing space by hiding the filter panel and focus on the results. To bring back the panel, simply click the menu icon [hamburger icon] located at the top left corner."
            [matTooltipPosition]="'above'" [matTooltipShowDelay]="3000">
            Close
          </button>
        </div>
        <div class="pango-drawer-body">
          <!-- <pango-search-aspect-form></pango-search-aspect-form> -->
          <pango-category-stats></pango-category-stats>
        </div>
      </div>
    </mat-drawer>
    <mat-drawer-content #scrollbarRef class="pango-section-body w-100-p">
      <div class="w-100-p" fxLayout="column" fxLayoutAlign="start stretch">
        <div class="pango-header accent w-100-p" fxLayout="row" fxLayoutAlign="start start">
          <div fxFlex="60%" fxLayout="column" fxLayoutAlign="start start">
            <h1>
              Functions of Human Genes
            </h1>
            <h2>
              The table below shows, for each human protein-coding gene, the set of functional characteristics that have
              been assigned based on expert review and integration of available experimental evidence in 6,333 families
              of protein-coding genes (<a [href]="pangoUtilService.getVersionedLink('/about/')" color="accent"> Read
                More</a>). Each
              characteristic is linked to the experimental evidence supporting
              it.</h2>


            <ng-container *ngIf="currentVersion === ApiVersion.V2024">
              <pango-version-banner> </pango-version-banner>
            </ng-container>
            <div class="mt-12 w-100-p" fxLayout="row" fxLayoutAlign="start center">
              <pango-gene-form> </pango-gene-form>
              <h3 class="ml-12">
                See any missing or incorrect functions? <a href="https://help.geneontology.org/" target="_blank">Let us
                  know!</a>
              </h3>
            </div>
          </div>

          <div fxFlex="" class="p-12" fxLayout="column" fxLayoutAlign="start start">

            <h2>PAN-GO Enrichment Analysis
              <i class="fa fa-question-circle"></i>
            </h2>
            <pango-overrep-form></pango-overrep-form>
          </div>
        </div>
        <div class="pango-summary-filter-bar" fxLayout="row" fxLayoutAlign="start center">
          <span *ngIf="annotationService.searchCriteria.filtersCount===0" (click)="clearAllFilters()"
            class="pango-no-info">
            No FIlters selected: You can filter the list to find a specific gene or function category.
          </span>

          <ng-container *ngIf="annotationService.searchCriteria.filtersCount>0">
            <small class="mr-12">Filtered By: </small>

            <mat-chip (click)="clearAllFilters()" class="pango-clearall-chip">
              Clear All
            </mat-chip>
          </ng-container>

          <mat-chip *ngIf="annotationService.searchCriteria[SearchFilterType.GENES].length>0" class="pango-filter-chip"
            [removable]="true" (removed)="removeFilter(SearchFilterType.GENES)"
            matTooltip="{{annotationService.searchCriteria.genesTooltip}}" [matTooltipPosition]="'below'"
            [matTooltipShowDelay]="2000">
            Genes <span> ({{
              annotationService.searchCriteria[SearchFilterType.GENES].length}})</span>
            <mat-icon matChipRemove>cancel</mat-icon>
          </mat-chip>

          <mat-chip *ngIf="annotationService.searchCriteria[SearchFilterType.SLIM_TERMS].length>0"
            class="pango-filter-chip" [removable]="true" (removed)="removeFilter(SearchFilterType.SLIM_TERMS)"
            matTooltip="{{annotationService.searchCriteria.slimTermsTooltip}}" [matTooltipPosition]="'below'"
            [matTooltipShowDelay]="2000">
            GO Function Categories <span> ({{
              annotationService.searchCriteria[SearchFilterType.SLIM_TERMS].length}})</span>
            <mat-icon matChipRemove>cancel</mat-icon>
          </mat-chip>

          <mat-chip *ngIf="annotationService.searchCriteria[SearchFilterType.ASPECTS].length>0"
            class="pango-filter-chip" [removable]="true" (removed)="removeFilter(SearchFilterType.ASPECTS)"
            matTooltip="{{annotationService.searchCriteria.aspectsTooltip}}" [matTooltipPosition]="'below'"
            [matTooltipShowDelay]="2000">
            Aspects <span> ({{
              annotationService.searchCriteria[SearchFilterType.ASPECTS].length}})</span>
            <mat-icon matChipRemove>cancel</mat-icon>
          </mat-chip>
        </div>
        <pango-summary-stats></pango-summary-stats>
        <pango-annotation-group class="w-100-p" [annotationPage]="annotationPage"></pango-annotation-group>
      </div>
      <div class="w-100-p">
        <pango-footer></pango-footer>
      </div>
    </mat-drawer-content>
    <mat-drawer #rightDrawer class="pango-right-drawer" mode="over" position="end">
      <div class="h-100-p" [ngSwitch]="pangoMenuService.selectedRightPanel">
        <pango-annotation-detail [panelDrawer]="rightDrawer" *ngSwitchCase="RightPanel.annotationDetail">
        </pango-annotation-detail>
      </div>
    </mat-drawer>
  </mat-drawer-container>
</div>

// site-react/src/app/home/Home.tsx
import type React from 'react';
import { useEffect, useState } from 'react';
import { Box, Chip, Tooltip } from '@mui/material';
import Genes from '../genes/Genes';
import GeneForm from '../genes/forms/GeneForm';
import OverrepForm from '../genes/forms/OverrepForm';
import { SearchFilterType } from '@/features/search/search';
import { setLeftDrawerOpen } from '@/@pango.core/components/drawer/drawerSlice';
import { useAppDispatch } from '../hooks';

// TODO: Add filters component

const Home: React.FC = () => {
  const dispatch = useAppDispatch();
  const [searchCriteria, setSearchCriteria] = useState({
    filtersCount: 0,
    [SearchFilterType.GENES]: [],
    [SearchFilterType.SLIM_TERMS]: [],
  });

  const clearAllFilters = () => {
    setSearchCriteria({
      filtersCount: 0,
      [SearchFilterType.GENES]: [],
      [SearchFilterType.SLIM_TERMS]: [],
    });
  };

  const removeFilter = (filterType: SearchFilterType) => {
    setSearchCriteria(prev => ({
      ...prev,
      [filterType]: [],
      filtersCount: prev.filtersCount - 1
    }));
  };

  useEffect(() => {
    dispatch(setLeftDrawerOpen(true));
  }, [dispatch]);

  return (
    <Box className="w-full flex flex-col">
      <div className="bg-gradient-to-r from-[#00174f] to-[rgba(0,23,79,0.5)] bg-cover bg-top relative h-[350px] min-w-[800px] max-h-[400px] p-5 pt-10"
        style={{
          backgroundImage: `linear-gradient(to right, #00174f, rgba(0,23,79,0.8), rgba(0,23,79,0.5)), url('/assets/images/gene.jpeg')`
        }}>
        <div className="flex">
          <div className="w-3/5 flex-col">
            <h1 className="text-4xl font-bold tracking-wider text-white mb-4">
              Functions of Human Genes
            </h1>
            <h2 className="text-lg leading-7 font-medium tracking-wider text-white mb-10 max-w-2xl">
              The table below shows, for each human protein-coding gene, the set of functional characteristics
              that have been assigned based on expert review and integration of available experimental evidence
              in 6,333 families of protein-coding genes.(<a className='text-accent-500 hover:text-accent-200'> Read
                More </a>). Each
              characteristic is linked to the experimental evidence supporting
            </h2>
            <div className='flex items-center'>
              <div className='w-[300px] mr-4'>
                <GeneForm />
              </div>

              <h3 className="text-xs text-white">
                See any missing or incorrect functions?
                <a href="https://help.geneontology.org/"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-accent-500 hover:text-accent-200">
                  Let us know!
                </a>
              </h3>
            </div>    </div>
          <div className="w-2/5 p-3">
            <h2 className="text-white text-sm font-medium">
              PAN-GO Enrichment Analysis
              <span className="ml-2">ⓘ</span>
            </h2>
            <OverrepForm />
          </div>
        </div>
      </div>

      <div className="sticky top-0 z-10 bg-white shadow-md px-3 h-[30px] flex items-center">
        {searchCriteria.filtersCount === 0 ? (
          <span className="text-gray-500 italic text-xs">
            No Filters selected: You can filter the list to find a specific gene or function category.
          </span>
        ) : (
          <div className="flex items-center gap-2">
            <small className="mr-3 text-xs">Filtered By:</small>
            <Chip
              label="Clear All"
              onDelete={clearAllFilters}
              className="h-6 text-xs"
              color="error"
              size="small"
            />
            {searchCriteria[SearchFilterType.GENES].length > 0 && (
              <Tooltip title="Click to remove genes filter" placement="bottom">
                <Chip
                  label={`Genes (${searchCriteria[SearchFilterType.GENES].length})`}
                  onDelete={() => removeFilter(SearchFilterType.GENES)}
                  className="h-6 text-xs"
                  size="small"
                />
              </Tooltip>
            )}
          </div>
        )}
      </div>

      <Box className="min-h-[500px] mb-[200px]">
        <Genes />
      </Box>
    </Box>
  );
};

export default Home;
