// site-angular/src/app/main/pages/gene/gene.component.ts
import { Component, OnDestroy, OnInit, ViewChild } from '@angular/core';
import { UntypedFormGroup } from '@angular/forms';
import { MatDrawer } from '@angular/material/sidenav';
import { ActivatedRoute } from '@angular/router';
import { RightPanel, LeftPanel } from '@pango.common/models/menu-panels';
import { PangoMenuService } from '@pango.common/services/pango-menu.service';
import { PangoUtils } from '@pango/utils/pango-utils';
import { Annotation } from 'app/main/apps/annotation/models/annotation';
import { AnnotationPage } from 'app/main/apps/annotation/models/page';
import { AnnotationService } from 'app/main/apps/annotation/services/annotation.service';
import { Gene } from 'app/main/apps/gene/models/gene.model';
import { environment } from 'environments/environment';
import { Subject, takeUntil } from 'rxjs';

@Component({
  selector: 'app-gene',
  templateUrl: './gene.component.html',
  styleUrls: ['./gene.component.scss']
})
export class GeneComponent implements OnInit, OnDestroy {

  RightPanel = RightPanel;
  LeftPanel = LeftPanel

  @ViewChild('leftDrawer', { static: true })
  leftDrawer: MatDrawer;

  @ViewChild('rightDrawer', { static: true })
  rightDrawer: MatDrawer;

  searchForm: UntypedFormGroup;
  leftPanelMenu;

  loadingSpinner: any = {
    color: 'primary',
    mode: 'indeterminate'
  };

  scrollbarConfig = {
    suppressScrollX: true
  }

  annotation: Annotation;
  geneId: string;
  hgncId;

  searchFormOptions: {
    hideGeneSearch: true
  }

  maxReferences = 150
  maxEvidences = 200

  tableOptions = {
    displayedColumns: [
      'term',
      'slimTerms',
      'evidence',
      'contributors'
    ]
  }

  private _unsubscribeAll: Subject<any>;


  constructor(private route: ActivatedRoute,
    public pangoMenuService: PangoMenuService,
    public annotationService: AnnotationService) {
    this._unsubscribeAll = new Subject();
    this.route
      .params
      .pipe(takeUntil(this._unsubscribeAll))
      .subscribe(params => {
        this.geneId = params['gene'] || null;

        const annotation = new Annotation()
        annotation.gene = this.geneId
        this.annotationService.searchCriteria.genes = [annotation]
        this.annotationService.updateSearch();
      });
  }

  ngOnInit(): void {
    this.pangoMenuService.setLeftDrawer(this.leftDrawer);
    this.pangoMenuService.setRightDrawer(this.rightDrawer);

    this.annotationService.onAnnotationsChanged
      .pipe(takeUntil(this._unsubscribeAll))
      .subscribe((annotationPage: AnnotationPage) => {
        if (annotationPage && annotationPage.annotations.length > 0) {
          this.annotation = annotationPage.annotations[0];
          this.hgncId = PangoUtils.getHGNC(this.annotation.longId);
        } else {
          this.annotation = null
        }
      });
  }

  ngOnDestroy(): void {
    this._unsubscribeAll.next(null);
    this._unsubscribeAll.complete();
  }

  getAGRLink() {

    if (this.hgncId) {
      return environment.agrPrefixUrl + this.hgncId;
    }

    return environment.agrPrefixUrl;

  }

  getUcscLink(element: Annotation) {
    const chr = `${element.coordinatesChrNum}:${element.coordinatesStart}-${element.coordinatesEnd}`
    return environment.ucscUrl + chr
  }

  getUniprotLink(gene: string) {
    const geneId = gene.split(':')

    if (geneId.length > 1) {
      return environment.uniprotUrl + geneId[1];
    }

    return gene;
  }

  getFamilyLink(element: Annotation) {

    return `${environment.pantherFamilyUrl}book=${encodeURIComponent(element.pantherFamily)}&seq=${encodeURIComponent(element.longId)}`
  }

}

<div class="w-100-p" fxLayout="row" fxLayoutAlign="start start">
  <mat-drawer-container class="w-100-p h-100-p" fxLayout="row" fxLayoutAlign="start start" autosize>

    <mat-drawer #leftDrawer class="pango-right-drawer" mode="side" position="start" opened="true">

    </mat-drawer>
    <mat-drawer-content #scrollbarRef class="pango-section-body w-100-p">
      <div *ngIf="annotation" class="w-100-p" fxLayout="column" fxLayoutAlign="start stretch">
        <div class="pango-gene-summary w-100-p" fxLayout="column" fxLayoutAlign="start stretch">
          <h1 class="pango-heading">
            <span class="pango-highlight">
              {{annotation.geneSymbol}}
            </span>: PAN-GO functions and evidence
          </h1>
          <div class="w-100-p" fxLayout="row" fxLayoutAlign="start space-between">
            <div class="pango-gene-detail-col" fxLayout="column" fxLayoutAlign="start start">
              <h2>
                Gene Information
              </h2>
              <div class="pango-term-row" fxLayout="row" fxLayoutAlign="start center">
                <div class="pango-title mr-8">
                  Gene:
                </div>
                <div class=" pango-description">
                  {{annotation.geneSymbol}}
                </div>
              </div>
              <div class="pango-term-row" fxLayout="row" fxLayoutAlign="start center">
                <div class="pango-title mr-8">
                  Protein:
                </div>
                <div class=" pango-description">
                  {{annotation.geneName}}
                </div>
              </div>

              <div class="pango-term-row" fxLayout="row" fxLayoutAlign="start center">
                <div class="pango-title mr-8">
                  Organism
                </div>
                <div class=" pango-description">
                  <a [href]="taxonApiUrl+annotation.taxonId" target="_blank">
                    {{annotation.taxonLabel}}
                  </a>
                </div>
              </div>

              <div class="pango-term-row" fxLayout="row" fxLayoutAlign="start center">
                <div class="pango-title mr-8">
                  GO annotations from all sources
                </div>
                <div class=" pango-description">
                  <a href="{{amigoGPUrl}}{{annotation.gene}}" target="_blank">
                    {{annotation.gene}}</a>
                </div>
              </div>
            </div>
            <div class="pango-links-col" fxLayout="column" fxLayoutAlign="start start">
              <h2>
                External Links
              </h2>
              <div class="pango-term-row" fxLayout="row" fxLayoutAlign="start center">
                <div class="pango-title mr-8">
                  UniProt ID:
                </div>
                <div class=" pango-description">
                  <a href="{{getUniprotLink(annotation.gene)}}" target="_blank">
                    {{annotation.gene}}
                  </a>
                </div>
              </div>
              <div class="pango-term-row" fxLayout="row" fxLayoutAlign="start center">
                <div class="pango-title mr-8">
                  PANTHER Tree Viewer:
                </div>
                <div class=" pango-description">
                  <a (click)="$event.stopPropagation()" [href]="getFamilyLink(annotation)" target="_blank">
                    {{annotation.pantherFamily}}
                  </a>
                </div>
              </div>
              <div class="pango-term-row" fxLayout="row" fxLayoutAlign="start center">
                <div class="pango-title mr-8">
                  UCSC Genome Browser:
                </div>
                <div class=" pango-description">
                  <a (click)="$event.stopPropagation()" [href]="getUcscLink(annotation)" target="_blank">
                    chr{{annotation.coordinatesChrNum}}:{{annotation.coordinatesStart}}-{{annotation.coordinatesEnd}}
                  </a>
                </div>
              </div>
              <div *ngIf="hgncId" class="pango-term-row" fxLayout="row" fxLayoutAlign="start center">
                <div class="pango-title mr-8">
                  Alliance of Genome Resources:
                </div>
                <div class=" pango-description">
                  <a [href]="getAGRLink()" target="_blank">
                    {{hgncId}}
                  </a>
                </div>
              </div>
              <div *ngIf="hgncId" class="pango-term-row" fxLayout="row" fxLayoutAlign="start center">
                <div class="pango-title mr-8">
                  HUGO Gene Nomenclature Committee:
                </div>
                <div class=" pango-description">
                  <a [href]="getHGNCLink()" target="_blank">
                    {{hgncId}}
                  </a>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="stat-header" fxLayout="row" fxLayoutAlign="start center" fxLayoutGap="48px">
          <div class="title-block" fxFlex="250px">
            <h2>Function summary</h2>
          </div>
          <div class="stat-block" fxLayout="row" fxLayoutAlign="start center">
            <div class="number">{{knowledgeCount['known']}}</div>
            <div class="label-group">
              <div class="label">Annotations</div>
              <div class="sublabel">(functional characteristics)</div>
            </div>
          </div>
          <div class="stat-block" fxLayout="row" fxLayoutAlign="start center">
            <div class="number">{{knowledgeCount['unknown']}}</div>
            <div class="label-group">
              <div class="label">Unknown function aspects</div>
            </div>
          </div>
        </div>

        <pango-gene-summary-table [summary]="annotation"></pango-gene-summary-table>


        <pango-annotation-table [annotations]="annotations" [options]="tableOptions" [maxReferences]="maxReferences"
          [maxEvidences]="maxEvidences" class="w-100-p"></pango-annotation-table>
      </div>
      <div class="w-100-p">
        <pango-footer></pango-footer>
      </div>
    </mat-drawer-content>
    <mat-drawer #rightDrawer class="pango-right-drawer" mode="over" position="end">
      <div class="h-100-p" [ngSwitch]="pangoMenuService.selectedRightPanel">
        <pango-annotation-detail [panelDrawer]="rightDrawer" *ngSwitchCase="RightPanel.annotationDetail">
        </pango-annotation-detail>
      </div>
    </mat-drawer>
  </mat-drawer-container>
</div>

// site-react/src/app/Gene.tsx
import { setLeftDrawerOpen } from '@/@pango.core/components/drawer/drawerSlice';
import { ENVIRONMENT } from '@/@pango.core/data/constants';
import AnnotationTable from '@/features/annotations/components/AnnotationTable';
import type { Annotation } from '@/features/annotations/models/annotation';
import { useGetAnnotationsQuery } from '@/features/annotations/slices/annotationsApiSlice';
import GeneSummary from '@/features/genes/components/GeneSummary';
import { transformTerms } from '@/features/genes/services/genesService';
import { useEffect } from 'react';
import { FiExternalLink } from 'react-icons/fi';
import { useParams } from 'react-router-dom';
import { useAppDispatch } from './hooks';
import { TermType } from '@/features/terms/models/term';


const Gene: React.FC = () => {
  const dispatch = useAppDispatch();
  const { id: geneId } = useParams<{ id: string }>();

  useEffect(() => {
    dispatch(setLeftDrawerOpen(false));
  }, [dispatch]);

  const filterArgs = { geneIds: [geneId] };
  const pageArgs = { page: 0, size: 200 };
  const { data: annotationsData } = useGetAnnotationsQuery({ filterArgs, pageArgs });

  const annotations = annotationsData?.annotations || [];

  const annotation = annotations && annotations.length > 0 ? annotations[0] : null;

  if (!annotation) {
    return <div className="p-4">Loading...</div>;
  }

  const knownTermTypes = annotations.filter(a => a.termType === TermType.KNOWN).length;
  const unknownTermTypes = annotations.filter(a => a.termType === TermType.UNKNOWN).length;

  const groupedTerms = transformTerms(annotations, 100);

  const getUniprotLink = (gene: string) => {
    const geneId = gene.split(':');
    return geneId.length > 1 ? `${ENVIRONMENT.uniprotUrl}${geneId[1]}` : gene;
  };

  const getFamilyLink = (element: Annotation) => {
    return `${ENVIRONMENT.pantherFamilyUrl}book=${encodeURIComponent(element.pantherFamily)}&seq=${encodeURIComponent(element.longId)}`;
  };

  return (
    <div className="w-full bg-slate-200">
      <div className="p-3 max-w-[1000px] mx-auto">
        {/* Gene Header Section */}
        <div className="pango-gene-summary w-full px-3 py-4">
          <h1 className="font-normal text-2xl mb-6">
            <span className="font-bold">{annotation.geneSymbol}</span>: PAN-GO functions and evidence
          </h1>

          <div className="flex  w-full">
            {/* Gene Information Column */}
            <div className="w-[300px] mr-[100px]">
              <h2 className="text-xl font-semibold mb-4">Gene Information</h2>
              <div className="space-y-1">
                <InfoRow label="Gene" value={annotation.geneSymbol} />
                <InfoRow label="Protein" value={annotation.geneName} />
                <InfoRow
                  label="Organism"
                  value={annotation.taxonLabel}
                  href={`${ENVIRONMENT.taxonApiUrl}${annotation.taxonId}`}
                />
                <InfoRow
                  label="GO annotations from all sources"
                  value={annotation.gene}
                  href={`${ENVIRONMENT.amigoGPUrl}${annotation.gene}`}
                />
              </div>
            </div>

            {/* External Links Column */}
            <div className="w-[300px]">
              <h2 className="text-xl font-semibold mb-4">External Links</h2>
              <div className="space-y-1">
                <InfoRow
                  label="UniProt ID"
                  value={annotation.gene}
                  href={getUniprotLink(annotation.gene)}
                />
                <InfoRow
                  label="PANTHER Tree Viewer"
                  value={annotation.pantherFamily}
                  href={getFamilyLink(annotation)}
                />
                <InfoRow
                  label="UCSC Genome Browser"
                  value={`chr${annotation.coordinatesChrNum}:${annotation.coordinatesStart}-${annotation.coordinatesEnd}`}
                  href={`${ENVIRONMENT.ucscUrl}chr${annotation.coordinatesChrNum}:${annotation.coordinatesStart}-${annotation.coordinatesEnd}`}
                />
              </div>
            </div>
          </div>
        </div>

        {/* Stats Header */}
        <div className="py-6 px-4 bg-gradient-to-r from-slate-100 to-white">
          <div className="flex items-center gap-12">
            <div className="w-[250px]">
              <h2 className="text-2xl font-semibold tracking-tight m-0">Function Summary</h2>
            </div>

            <StatBlock
              number={knownTermTypes}
              label="Annotations"
              sublabel="(functional characteristics)"
            />

            <StatBlock
              number={unknownTermTypes}
              label="Unknown function aspects"
            />
          </div>
        </div>
        {annotations.length > 0 && (
          <div className="w-full bg-white py-4">
            <GeneSummary groupedTerms={groupedTerms} />
          </div>
        )}
        <div className="py-6 px-4 bg-gradient-to-r from-slate-100 to-white">
          <h2 className="text-2xl font-semibold tracking-tight m-0">Function Details</h2>
        </div>
        {annotations.length > 0 && (
          <div className="w-full bg-white py-4">
            <AnnotationTable annotations={annotations} />
          </div>
        )}
      </div>
    </div>
  );
};

interface InfoRowProps {
  label: string;
  value: string;
  href?: string;
}

const InfoRow: React.FC<InfoRowProps> = ({ label, value, href }) => (
  <div className="flex items-center p-[5px]">
    <span className="text-xs pr-2 text-gray-700">
      {label}:
    </span>
    {href ? (
      <a
        href={href}
        target="_blank"
        rel="noopener noreferrer"
        className="text-gray-500 hover:text-gray-700 flex items-center gap-1"
      >
        {value}
        <FiExternalLink className="w-3 h-3" />
      </a>
    ) : (
      <span className="text-gray-500">{value}</span>
    )}
  </div>
);

interface StatBlockProps {
  number: number;
  label: string;
  sublabel?: string;
}

const StatBlock: React.FC<StatBlockProps> = ({ number, label, sublabel }) => (
  <div className="flex items-center pl-6">
    <span className="text-5xl font-bold text-[#1976d2] mr-4 min-w-[60px] text-center">
      {number}
    </span>
    <div className="label-group">
      <div className="text-base font-medium mb-1">{label}</div>
      {sublabel && <div className="text-sm font-normal text-gray-600">{sublabel}</div>}
    </div>
  </div>
);

export default Gene;
